version: '3.3'

services:
  postgres:
    image: postgres:latest
    volumes:
      - ./user.sql:/docker-entrypoint-initdb.d/user.sql
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"